### ISSUE TITLE
Player sticks to vertical walls

### ISSUE THREAD

**Issue by rex8112** [gadsu/cleanup#15]
**Description of bug**
When the player jumps while near a wall and moving towards a wall, as long as the movement key in the direction of the wall is held the player will stick to the wall/platform tile.

**To Reproduce**
1. Go to 'move towards any tile with a vertical face'
2. Click on ' "A" or "D" + "W" '
3. See error

**Expected behavior**
the player bounces back with the same horizontal velocity they hit the wall with. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6889658/46557978-45c36500-c8b1-11e8-92dd-28244f639ee5.png)

Made by Carl and Riley

**Comment by rex8112** [comment]
Fixed as of commit 690ba603b2e4533c09662d5786e2bb1a0080bdf7

**Comment by cjpetersen** [comment]
This bug is not fixed for all cases still true for floating platforms and some walls even trap you permanently even after all keys have been released.   

[stuckOnWalls.zip](https://github.com/gadsu/cleanup/files/2591322/stuckOnWalls.zip)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make a list of issues reported by Nanocon play testing (.5)](https://trello.com/c/lQSkcoU7/267-make-a-list-of-issues-reported-by-nanocon-play-testing-5)

**Comment by cjpetersen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update GitHub Issue labels and add new issues/ test to make sure issues have been solved](https://trello.com/c/zQ4vKUbH/268-update-github-issue-labels-and-add-new-issues-test-to-make-sure-issues-have-been-solved)

**Comment by rex8112** [comment]
Probably would've made a new issue. The reasoning for this is vastly different
