### ISSUE TITLE
slime pickup does not work green level

### ISSUE THREAD

**Issue by rachelgroth** [gadsu/cleanup#45]
**Branch or release bug is on**
programming
**If found on Unity editor, what scene did you load**
_dontdestroyonload
**Describe the bug**
upon beginning the game and completing tutoriallevel, greenlevel does not work for picking up slime, something to do with the slider

**To Reproduce**
go to _dontdestroyonload
click start
go to end of level
interact with end
attempt to pick up slime

**Expected behavior**
the slime pick up

**Screenshots**
![image](https://user-images.githubusercontent.com/38136112/51874685-9579e080-2327-11e9-9cd0-1431fb0ecdbb.png)

**Additional context**
this is fucking bullshit

**Comment by rex8112** [comment]
Should be working now, sceneLoaded was getting set to false before the scene change.

**Comment by IanTrollinger** [comment]
Still doesn't work. I tried a full play through of what we have so far starting from tutorial to the end of the green level. When I entered the green level, I was unable to pick up slime or wall jump. I tried loading it from the Save/Load and it worked perfectly. I think the test for this will need to be played from the tutorial until the Green level.

**Comment by IanTrollinger** [comment]
Sorry was testing in master not programming.
